* Ferry's personal org
** Work
*** DONE [#C] PMP workshop serial in every thursday morning from Nov.
    SCHEDULED: <2013-11-01 Fri>
    2012, including ten sessions.
*** 19475.801&802 : FR: ATCA SGSN Frame Relay phase 2 step 1
**** Collection
***** 1) FRIU can not changed from WO-EX downward if the other
      FRIU is not in WO-EX
***** 2) Each SCNAM card has 4 STM-1/OC-3 interfaces and each
      interface is considered as one SET unit, thus FRIU has
      4 child unit SET.in ETSI environment, there are 63 ET
      for STM-1 interface, and in ANSI, 84 ET for OC-3
      interface.
***** 3) As STM-1/OC-3 interface unit, FRIU share the similar SDH
      hierarchy unit structure as its classical counterpart
      STMU.Which means ET group creation and deletion for each
      STM-1/OC3 interface is supported. During the creation of
      ET group corresponding SET unit will be created
      automatically.
***** 4) RYEPRO PROCEDURE check_unit_connections checks
      connection_inquiry_s every 1s timeout for every ET.In
      other words, RYEPRO will be blocked here about 63/84 seconds
      without handle any other tasks.
** Life
*** TODO [#B] Daily exercise in company
    SCHEDULED: <2012-10-08 Mon>
    :PROPERTIES:
    :STYLE:  habit
    :ORDERED:  t
    :END:
** Digest
*** DONE [#B] Mythical Man-Month
    SCHEDULED: <2012-11-30 Fri>
    :PROPERTIES:
    :ORDERED:  t
    :END:
** Balance
*** DONE Purchase and receive the Badmiton Racket from taobao.com[2012-05-04 Fri]
*** DONE [#B] Plan a hiker to PizzaHut in Linping<2012-05-05 Sat>
*** DONE Fill the application to claim payment of treatment in hospital
    SCHEDULED: <2012-10-12 Fri>
    :PROPERTIES:
    :ORDERED:  t
    :END:
    
*** DONE [#B] Clean Code
    SCHEDULED: <2012-10-31 Wed>
    :PROPERTIES:
    :ORDERED:  t
    :END:
