
http://www.cnblogs.com/holbrook/archive/2012/04/12/2444992.html
http://orgmode.org/orgcard.txt

video
http://v.youku.com/v_show/id_XNjA2MDEyMDg0.html?from=s1.8-1-1.2
http://v.youku.com/v_show/id_XNTc0NTUyMDU2.html?from=s1.8-1-1.2

* 1: 大纲
** 大纲相关的快捷键 
*** 1.2.1 折叠大纲
快捷键	命令                说明
S-TAB	org-shifttab    循环切换整个文档的大纲状态（三种状态：折叠，打开下一级，打开全部）
TAB	    org-cycle	    循环切换光标所在大纲的状态

*** 1.2.2 在大纲之间移动
快捷键                  命令	说明
C-c C-n/p	 		下/上一标题
C-c C-f/b	 		下/上一标题（仅限同级标题）
C-c C-u             跳到上一级标题
C-c C-j             切换到大纲浏览状态

*** 1.2.3 基于大纲的编辑  
快捷键                      命令	说明
M-RET	            	插入一个同级标题             C-RET insert after current title
M-S-RET	 	            插入一个同级TODO 标题		  C-S-RET insert same level todo after current title
M-LEFT/RIGHT	 	    将当前标题升/降级
M-S-LEFT/RIGHT	 	    将子树升/降级                      
M-S-UP/DOWN	            将子树上/下移                M-UP/DOWN
C-c *	 	            将本行设为标题/正文
C-c C-w                 将子树或区域移动到另一标题处（跨缓冲区）
C-x n s/w	 	        只显示当前子树/返回
C-c C-x b	 	        在新缓冲区显示当前分支（类似C-x n s)
C-c /	 	            只列出包含搜索结果的大纲，并高亮，支持多种搜索方式
C-c C-c	 	            取消高亮
更多的快捷键可以通过C-c C-x C-h查看。

** "TODO" items
================================================================================
TODO Items and Checkboxes
================================================================================

rotate the state of the current item              C-c C-t                    *
select next/previous state                        S-LEFT/RIGHT               * 
select next/previous set                          C-S-LEFT/RIGHT
toggle ORDERED property                           C-c C-x o
view TODO items in a sparse tree                  C-c C-v,
view 3rd TODO keyword's sparse tree               C-3 C-c C-v

set the priority of the current item              C-c , [ABC]
remove priority cookie from current item          C-c , SPC
raise/lower priority of current item              S-UP/DOWN\notetwo

insert new checkbox item in plain list            M-S-RET
toggle checkbox(es) in region/entry/at point      C-c C-x C-b
toggle checkbox at point                          C-c C-c
update checkbox statistics (C-u : whole file)     C-c #

** DONE test1
   SCHEDULED: <2016-07-08 周五>
   
** 大纲的显示方式
默认的大纲显示没有缩进，显得有些乱。可以用 M-x org-indent-mode切换到另一种显示方式：
如果想让某个文件默认用这种方式打开，可以在文件头部增加：
“#+STARTUP: indent”
如果希望打开所有org文件都默认用这种方式，可以在.emacs中配置：
(setq org-startup-indented t)

** TODO test2
   DEADLINE: <2016-07-25 周一>

* 3: 轻量级标记语言====================================
** 3.1 字体
*粗体*
/斜体/
+删除线+
_下划线_
下标： H_2 O
上标： E=mc^2
等宽字：  =git=  或者 ～git～

** 3.2 表格
Org 能够很容易地处理 ASCII 文本表格。任何以‘|’为首个非空字符的行都会被认为是表格的一部分。’|‘也是列分隔符。一个表格是下面的样子：
| Name  | Pone | Age |
|-------+------+-----|
| Peter | 1234 | 17  |
| Anna  | 4321 | 25  |
你可能认为要录入这样的表格很繁琐，实际上你只需要输入表头“|Name|Pone|Age”之后，按C-c RET,就可以生成整个表格的结构。类似的快捷键还有很多：

3.2.1 创建和转换表格
快捷键	命令	说明
C-c 竖线	 	创建或转换成表格
4x5 (x is x key, not *)

3.2.2 调整和区域移动 
快捷键	命令	说明
C-c C-c	 	调整表格，不移动光标
TAB	 	移动到下一区域，必要时新建一行
S-TAB	 	移动到上一区域
RET	 	移动到下一行，必要时新建一行

3.2.3 编辑行和列 
快捷键	命令	说明
M-LEFT/RIGHT	 	移动列
M-UP/DOWN       	移动行
M-S-LEFT/RIGHT	 	删除/插入列
M-S-UP/DOWN	 	删除/插入行
C-c -	 	添加水平分割线
C-c RET	 	添加水平分割线并跳到下一行
C-c ^	 	根据当前列排序，可以选择排序方式

** 3.3 段落
对于单个回车换行的文本，认为其属于同一个段落。在导出的时候将会转化为不换行的同一段。如果要新起一个段落，需要留出一个空行。 这点与MediaWiki类似。

** 3.4 列表
Org 能够识别有序列表、无序列表和描述列表。

无序列表项以‘-’、‘+’或者‘*‘开头。
有序列表项以‘1.’或者‘1)’开头。
描述列表用‘::’将项和描述分开。
有序列表和无序列表都以缩进表示层级。只要对齐缩进，不管是换行还是分块都认为是处于当前列表项。
同一列表中的项的第一行必须缩进相同程度。当下一行的缩进与列表项的的开头的符号或者数字相同或者更小时，这一项就结束了。当所有的项都关上时，或者后面有两个空行 时，列表就结束了。例如：

  My favorite scenes are (in this order)
  1. The attack of the Rohirrim
  2. Eowyn's fight with the witch king
      + this was already my favorite scene in the book
      + I really like Miranda Otto.
  Important actors in this film are:
  - Elijah Wood :: He plays Frodo
  - Sean Austin :: He plays Sam, Frodo's friend.
将显示为：

My favorite scenes are (in this order)

The attack of the Rohirrim
Eowyn's fight with the witch king
this was already my favorite scene in the book
I really like Miranda Otto.
Important actors in this film are:

Elijah Wood
He plays Frodo
Sean Austin
He plays Sam, Frodo's friend.
3.4.1 列表操作快捷键
为了便利，org-mode也支持很多列表操作的快捷键，大部分都与大纲的快捷键类似：

 
快捷键	命令	说明
TAB	 	折叠列表项
M-RET	 	插入项
M-S-RET	 	插入带复选框的项
M-S-UP/DOWN	 	移动列表项
M-LEFT/RIGHT	 	升/降级列表项，不包括子项
M-S-LEFT/RIGTH	 	升/降级列表项，包括子项
C-c C-c	 	改变复选框状态
C-c -	 	更换列表标记（循环切换）

** 3.5 分隔线
五条短线或以上显示为分隔线。


* 4: tag
**  标记tag
在Org-mode中，可以对标题增加tag标记。标记的格式如下：
跟特留尼西特握手                    :苦差:薪水:逃不掉:
而且Org-mode的标签自动按照大纲树的结构继承。即子标题自动继承父标题的标签。比如：
'* Meeting with the French group                                        :work:
'** Summary by Frank                 :boss:notes:
'*** TODO Prepare slides for him     :action:
则最后一行标题具有 work, boss, notes, action 四个标签。

如果希望文档中的所有标题都具有某些标签，只需要定义文档元数据：
#+FILETAGS: :Peter:Boss:Secret:
如果手工输入标签，在标题后设置标签，键入:后，M-Tab自动提供标签的补齐。
更方便的做法是在正文部分用C-c C-q 或直接在标题上用C-c C-c创建标签，这种方式可以列出所有预定义的标签以便选取。 

**  按tag搜索
使用标签可以更好的管理内容。org-mode提供了以下功能：

KEYS	COMMENT
C-c \	按tag搜索标题
C-c / m	搜索并按树状结构显示
C-c a m	按标签搜索多个文件（需要将文件加入全局agenda)
可以使用逻辑表达式限制条件，更准确灵活的搜索

+     和      a+b     同时有这两个标签
-     排除    a-b     有 a 但没有 b
|     或      a|b     有 a 或者有 b
&     和      a&b     同时有 a 和 b，可以用“+”替代
在查询视图中 C-c C-c 退出


* 5: 导出
C-c C-e a 导出为文本文件。 C-c C-e h 导出为 HTML 文件
